Make the config file overridable
u1f35c/mqtt-arp pull request #3
Opened 2023-06-10 20:02 UTC by claes

2023-06-13 09:17 UTC, u1f35c commented
Seems like a reasonable thing to add, but a few comments on the implementation.

2023-06-13 09:18 UTC, u1f35c requested changes

2023-06-13 09:18 UTC, u1f35c commented on mqtt-arp.c
> +		printf("Could not read config file %s\n", file);
Output to stderr? `fprintf(stderr, …`

2023-06-13 09:18 UTC, u1f35c commented on mqtt-arp.c
> +		c = getopt_long(argc, argv, "f:", long_options, &option_index);
Running through `getopt_long` twice feels a bit clunky. Perhaps have 2 instances of the `ma_config` struct, one we fill out from the command line arguments then one we read from the config file, then override the config file with anything non-NULL from the command line?

2023-06-13 09:18 UTC, u1f35c commented on README.md
> +There is basic configuration file support; by default ```mqtt-arp``` will read ```/etc/mqtt-arp.conf```. The location can be overridable, see below.
"overridden"

2023-06-13 09:56 UTC, claes commented
Thanks for the feedback. My C is very rusty but I will attempt to address your points

2023-06-14 20:37 UTC, claes commented on README.md
> +There is basic configuration file support; by default ```mqtt-arp``` will read ```/etc/mqtt-arp.conf```. The location can be overridable, see below.
Fixed

2023-06-14 20:38 UTC, claes commented on mqtt-arp.c
> +		c = getopt_long(argc, argv, "f:", long_options, &option_index);
Yes agreed. I have now changed the approach as per suggestion.

2023-06-14 20:38 UTC, claes commented on mqtt-arp.c
> +		printf("Could not read config file %s\n", file);
Updated

2023-06-14 20:42 UTC, claes commented
Changed the approach to use two structs, and let one override the other.

2023-07-11 17:41 UTC, u1f35c commented
Thanks! Merged with some formatting fix-ups - please try to ensure you keep to the existing style when submitting diffs (e.g. indentation using tabs, not spaces).

2023-07-11 17:41 UTC, closed without merging